---
- name: Power on VMware virtual machines
  hosts: localhost
  gather_facts: no
  vars_files:
    - vars.yml
    - var_remove_vm.yml
  tasks:
    - name: Power on VM
      community.vmware.vmware_guest_powerstate:
        hostname: "{{ esxi_hostname }}"
        username: "{{ esxi_username }}"
        password: "{{ esxi_password }}"
        validate_certs: no
        name: "{{ item.name }}"
        state: powered-off
      loop: "{{ vm_list }}"  
      delegate_to: localhost
    - name: Delete VM
      community.vmware.vmware_guest:
        hostname: "{{ esxi_hostname }}"
        username: "{{ esxi_username }}"
        password: "{{ esxi_password }}"
        validate_certs: no
        name: "{{ item.name }}"
        state: absent
      loop: "{{ vm_list }}"  
      delegate_to: localhost

