---
- name: create_multi_vm
  hosts: localhost
  strategy: free
  gather_facts: no
  vars_files:
    - var.yml
    - var_create_vm.yml
  tasks:
    - name: create_VM
      community.vmware.vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        name: "{{ item.name }}"
        datacenter: "{{ datacenter_name }}"
        state: powered-on
        folder: "{{ folder_vm }}"
        guest_id: "otherGuest64"              
        disk:
          - size_gb: "{{ vm_disk_size }}"
            type: thin
            datastore: "{{ datastore_name }}"
        hardware:
          memory_mb: "{{ vm_memory }}"
          num_cpus: "{{ vm_cpu }}"
        cdrom:
          -  type: "iso"
             iso_path: "{{ iso_path }}"
             controller_number: 0
             controller_type: ide
             unit_number: 0
      async: 600
      poll: 0
      loop: "{{ vm_list }}"
      register: async_jobs
      delegate_to: localhost
    - name: Wait for all VM creation jobs to complete
      async_status:
        jid: "{{ item.ansible_job_id }}"
      register: job_results
      until: job_results.finished
      retries: 30
      delay: 10
      loop: "{{ async_jobs.results }}"
      
    - name: Configure IPs on VMs
      community.vmware.vmware_guest_network:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        name: "{{ item.name }}"
        datacenter: "{{ datacenter_name }}"
        networks:
          - name: "{{ item.network }}"
            ip: "{{ item.ip }}"
            netmask: "{{ item.netmask }}"
            gateway: "{{ item.gateway }}"
      loop: "{{ vm_list }}"
      loop_control:
        label: "{{ item.name }}"
      async: 600
      poll: 0
      register: ip_configure_jobs
